# Generated by Django 4.2.13 on 2024-06-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
