# Generated by Django 4.2.13 on 2024-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Phone')),
                ('message', models.CharField(blank=True, max_length=150, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
