# Generated by Django 4.2.13 on 2024-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='RuService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=550)),
            ],
        ),
    ]
